### PR TITLE
test 2 added

### PR DESCRIPTION
**Pull request by learning44code**
hello
pls check test 2, and approve.
regards
ironman

### CODE REVIEW

**Comment by learning4code** [comment]
hello,
code looks fine, add test 3
regards
batman

**Comment by learning44code** [comment]
hello
i added test 3
regards,
ironman

**Comment by learning4code** [comment]
dude its ok, go for merge
regards
batman

**Comment by learning44code** [comment]
ok dude, im going for merge.
thanks batman for your useless time.

**Pull request merged**
